"""0_6_0

迁移 ID: 7420f69398ee
父迁移: a9a3810efa4a
创建时间: 2024-12-31 13:05:54.230735

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = '7420f69398ee'
down_revision: str | Sequence[str] | None = 'a9a3810efa4a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alchelper_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alchelper_record_id'), ['id'], unique=True)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alchelper_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alchelper_record_id'))

    # ### end Alembic commands ###
